#!/bin/bash
ip link set dev eth0 up
ip addr add 31.4.254.1/26 dev eth0
ip link set dev eth1 up
ip addr add 31.4.254.66/26 dev eth1
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add default via 31.4.254.65
#ip route add 192.168.139.128/25 via 31.4.254.5

