#!/bin/bash
ip link set dev eth0 up
ip addr add 192.168.139.129/25 dev eth0
ip link set dev eth1 up
ip addr add 31.4.254.5/26 dev eth1
echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add default via 31.4.254.1
service isc-dhcp-server start 
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
# Bloquer toutes les requêtes sauf celles filtrées
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
# Accepter Ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT
# Accepter DHCP
iptables  -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT
# Accpeter DNS
iptables -t filter -A FORWARD -d 31.4.254.200/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.254.200/26 -p udp --sport 53 -j ACCEPT
# Accpeter HTTP
iptables -t filter -A FORWARD -d 31.4.254.230/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.254.230/26 -p tcp --sport 80 -j ACCEPT
# Accepter FTP
iptables -A FORWARD -d 31.4.254.230/26 -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -s 31.4.254.230/26 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024: --dport 1024: -j ACCEPT


