#!/bin/bash
ip link set dev eth0 up
ip addr add 31.4.254.65/26 dev eth0
ip link set dev eth1 up
ip addr add 31.4.254.131/26 dev eth1
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add 31.4.254.192/26 via 31.4.254.129
#ip route add default via 31.4.254.66
