#!/bin/bash
ip link set dev eth0 up
ip addr add 31.4.254.129/26 dev eth0
ip link set dev eth1 up
ip addr add 31.4.254.193/26 dev eth1
#echo 1 > /proc/sys/net/ipv4/ip_forward
#ip route add default via 31.4.254.131

## Filtres
# Bloquer toutes les requêtes sauf celles filtrées
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP
# Accepter ping
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT
# Accepter Rip routing
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT
# Accepter DNS
iptables -t filter -A FORWARD -d 31.4.254.200/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.254.200/26 -p udp --sport 53 -j ACCEPT
# Accepter HTTP
iptables -t filter -A FORWARD -d 31.4.254.230/26 -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -s 31.4.254.230/26 -p tcp --sport 80 -j ACCEPT
# Accepter FTP
iptables -A FORWARD -d 31.4.254.230/26 -p tcp --dport 21 -j ACCEPT
iptables -A FORWARD -s 31.4.254.230/26 -p tcp --sport 21 -j ACCEPT
iptables -A FORWARD -p tcp --sport 1024: --dport 1024: -j ACCEPT

