<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JEU" nsURI="http://www.n7.fr/JEU" nsPrefix="JEU">
  <eClassifiers xsi:type="ecore:EClass" name="Jeu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jeuelement" upperBound="-1"
        eType="#//JeuElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JeuElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Joueur" eSuperTypes="#//JeuElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taille" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lieu" eType="#//Endroit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connaissance" upperBound="-1"
        eType="#//Connaissance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocateurObjetJoueur"
        upperBound="-1" eType="#//AllocateurObjetJoueur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Endroit" abstract="true" eSuperTypes="#//JeuElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connaissance" upperBound="-1"
        eType="#//Connaissance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocateurObjetLieu" upperBound="-1"
        eType="#//AllocateurObjetLieu" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connaissance" eSuperTypes="#//JeuElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilite" eType="#//Typevisibilite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Conditions_visibilite"
        ordered="false" upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocateurObjetJoueur">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboccurence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objet" eType="#//Objet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proprietaire" eType="#//Joueur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocateurObjetLieu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nboccurence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objet" eType="#//Objet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proprietaire" eType="#//Endroit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objet" eSuperTypes="#//JeuElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taille" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilite" eType="#//Typevisibilite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Conditions_visibilite"
        ordered="false" upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estVerifie" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="info" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Personne" eSuperTypes="#//JeuElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Interaction" eType="#//Interaction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilite" eType="#//Typevisibilite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Conditions_visibilite"
        ordered="false" upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action_du_choix" lowerBound="1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Typevisibilite">
    <eLiterals name="Visible" literal="visible"/>
    <eLiterals name="Invisible" value="1" literal="invisible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OuvertOuferme">
    <eLiterals name="Ouvert" literal="ouvert"/>
    <eLiterals name="Ferme" value="1" literal="ferme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Victime" lowerBound="1"
        upperBound="-1" eType="#//Joueur"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Debut" eSuperTypes="#//Lieu_generique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Chemin_suivant" lowerBound="1"
        upperBound="-1" eType="#//Chemin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chemin" eSuperTypes="#//Endroit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lieu_precedent" lowerBound="1"
        eType="#//Lieu_generique"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lieu_suivant" lowerBound="1"
        eType="#//Lieu_generique"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_possible_chemin"
        upperBound="-1" eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Accessibilite" lowerBound="1"
        eType="#//OuvertOuferme"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Condition_ouverture" eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visibilite" eType="#//Typevisibilite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Conditions_visibilite"
        ordered="false" upperBound="-1" eType="#//Condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="joueur" eType="#//Joueur"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personne" eType="#//Personne"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choix" upperBound="-1"
        eType="#//Choix" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieu" eSuperTypes="#//Lieu_generique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Chemin_sortants" lowerBound="1"
        upperBound="-1" eType="#//Chemin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Chemin_entrants" lowerBound="1"
        upperBound="-1" eType="#//Chemin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Interactions" upperBound="-1"
        eType="#//Personne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fin" eSuperTypes="#//Lieu_generique">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Chemin_entrants" lowerBound="1"
        upperBound="-1" eType="#//Chemin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lieu_generique" abstract="true" eSuperTypes="#//Endroit"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action_consommation" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Consommation_objet" upperBound="-1"
        eType="#//Objet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_attribution" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action_attribution_connaissance" eSuperTypes="#//Action_attribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attribution_connaissance"
        upperBound="-1" eType="#//Connaissance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_attribution_objet" eSuperTypes="#//Action_attribution">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attribution_objet" upperBound="-1"
        eType="#//Objet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition_objet" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition_objet" eType="#//AllocateurObjetJoueur"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb_occurence_objet_min"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nb_occurence_objet_max"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition_connaissance" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition_connaissance"
        eType="#//Connaissance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Contrainte_connaissance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
